spring.application.name=MoneyApp

# H2 i fil-modus (dataene blir lagret mellom hver gang du starter)
spring.datasource.url=jdbc:h2:file:./data/moneyapp
spring.datasource.username=sa
spring.datasource.password=

# La Hibernate lage og oppdatere tabellene automatisk
spring.jpa.hibernate.ddl-auto=update

# Webkonsoll for å se i databasen: http://localhost:8080/h2-console
spring.h2.console.enabled=true
